type: go
runtime: ghcr.io/nextmv-io/runtime/default:latest

build:
  command: bash .nextmv/build.sh
  environment:
    ARCH: arm64 # Use x64 for amd... execution classes
files:
  - main
configuration:
  content:
    format: "json"
