[package]
name = "goodlp-knapsack"
version = "0.1.0"
edition = "2024"

[dependencies]
good_lp = { version = "1.14.0", features = ["highs"], default-features = false}
clap = { version = "4.5.7", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
